# Generated by Django 5.2.7 on 2025-11-26 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('subTopic', models.CharField(blank=True, max_length=200)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.TextField()),
                ('correctness', models.BooleanField(blank=True, null=True)),
                ('why_correct', models.TextField(blank=True)),
                ('num', models.IntegerField(help_text='Position/order within the quiz')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='adaptiveLearning.quiz')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='adaptiveLearning.quiz')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('session_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_id'],
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user', 'topic'], name='adaptiveLea_user_id_58e96c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'num')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['quiz', 'name'], name='adaptiveLea_quiz_id_27f372_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'session_active'], name='adaptiveLea_user_id_0dd477_idx'),
        ),
    ]
