# Generated by Django 5.2.7 on 2025-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptiveLearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Difficulty level: 1 (easy) to 5 (hard)'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='MCQ options including correct answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='source_reference',
            field=models.TextField(blank=True, help_text='Reference to source material'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='why_correct',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer'),
        ),
    ]
