# Generated by Django 5.2.7 on 2025-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptiveLearning', '0002_question_answered_at_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='grade',
        ),
        migrations.AddField(
            model_name='quiz',
            name='field_of_study',
            field=models.CharField(blank=True, help_text='Field of study (e.g., Computer Science, Biology)', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='publication_year',
            field=models.CharField(blank=True, help_text='Publication year range (e.g., 2020-)', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='semantic_scholar_data',
            field=models.JSONField(blank=True, help_text='Retrieved papers from Semantic Scholar', null=True),
        ),
    ]
