# Generated by Django 5.2.7 on 2025-12-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptiveLearning', '0003_remove_quiz_grade_quiz_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='prompt',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subTopic',
            field=models.CharField(help_text='Specific topic within the field', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(help_text='Field of study (e.g., Computer Science, Biology)', max_length=200),
        ),
    ]
